### PR TITLE
Show appropriate message on a PR close

### LINKED ISSUE #66: Pushing a commit while hoff is integrating causes a wrong comment to be sent
After summoning hoff, I added another commit to the pull request while hoff was waiting for CI. This caused hoff to comment: ‘Abandoning this pull request because it was closed.’

Quoting @ruuda:

> A new push should clear the integration status, and Hoff did leave a comment to clarify that it would take no further action, which is good. The bug is that a commit change event is handled as a close followed by a re-open: https://github.com/channable/hoff/blob/959aa1e07bd797e888cf4d9ad2ceba6bd615ac63/src/Logic.hs#L244-L250. If you like you can add a test case to Hoff to reproduce this scenario, and then fix it. An appropriate fix would be to inline `handlePullRequestClosed` and specialize the message to that situation, because it is still nice to get feedback when Hoff abandons a pull request.

### PR DESCRIPTION
**Pull request by adrianotm**
Fixes #66

### CODE REVIEW

File: src/Logic.hs [hunk 1]
```diff
@@ -311,11 +315,20 @@ handlePullRequestCommitChanged prId newSha state =
...
 
+-- | Describe what caused the PR to close.
+prClosingMessage :: PRCloseCause -> Text
+prClosingMessage User = "Abandoning this pull request because it was closed."
+prClosingMessage StopIntegration = "Stopping integration because the PR changed after approval."
+
+-- | Handle PR close when a user actually closes a PR.
 handlePullRequestClosed :: PullRequestId -> ProjectState -> Action ProjectState
-handlePullRequestClosed pr state = Pr.deletePullRequest pr <$>
+handlePullRequestClosed = handlePullRequestClosed' User
```
Comment (FPtje) [inline src/Logic.hs:325]: It would be better to call this `handlePullRequestClosedByUser`, because a single apostrophe does not tell the reader what the difference between the functions is.

**Review by FPtje — CHANGES_REQUESTED** [review]
Looking good! Here's an initial review. Maybe @marcin-rzeznicki wants to take a look at it as well

**Review by marcin-rzeznicki — APPROVED** [review]
Aside from reconsidering the naming as @FPtje pointed out - LGTM! Short and sweet.

**Review by FPtje — APPROVED** [review]
LGTM!

**Comment by adrianotm** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @adrianotm, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 6f69633ae07c644964d7ece9b7e63a7fc934967a, waiting for CI …
