### PR TITLE
Enforce consistency between comment and action

### LINKED ISSUE #53: Enforce consistency between acknowledgement comment and actual action
## Problem

Currently, when a user leaves a comment on a pull request that is detected as an approval, Hoff immediately leaves a comment to acknowledge the approval. In the comment, it says what action it is going to take: https://github.com/channable/hoff/blob/3b525b2f285d37766612ac6a559f603efa5c2898/src/Logic.hs#L288-L322

This means we have duplicate logic: once to leave the comment, and once when actually executing it. This has bitten us multiple times:

* https://github.com/channable/hoff/pull/36 (acknowledging unknown pull requests)
* When you leave an approval comment on a PR that failed to build, nothing happens (it will remain approved, and it will remain failed), but we still acknowledge it (still an unresolved bug).

Also, when an event happens that clears the approval status (such as pushing a new commit), we have no feedback for this.

## Proposed solution

Rather than commenting immediately what action we will take, we can have a per-PR flag “needs feedback”. When we modify a pull request (for example, because it was approved), we set this flag. Then at the end of handling events, we can go over all PRs that need feedback, post a comment about its current status, and clear the flag. The update would then be based on the true state, and not on a prediction of what we expect to do.

### PR DESCRIPTION
**Pull request by splintah**
Leave comments based on the actual status of the PR.

This pull request should eventually fix #53.

### CODE REVIEW

**Comment by splintah** [comment]
@ruuda, is this sort of what you meant?

If so, should other `leaveComment`s be moved into `feedback` too? To do that, I think it would be useful to add some data to `PullRequestStatus`; the sha after integration, for example.

**Comment by ruuda** [comment]
>  To do that, I think it would be useful to add some data to PullRequestStatus; the sha after integration, for example.

I haven’t looked at the PR yet, but this data is present in `IntegrationStatus`, we could add it to `PullRequestStatus`, sure. A larger change that I still want to do, similar to #59, is to merge the approval status and the integration status. That on the one hand enforces at the type level that only approved PRs can be integrated, and it would also eliminate the need for `PullRequestStatus` entirely. That would be a rather large change though, so let's not do that for this issue.

File: src/Logic.hs [hunk 1]
```diff
@@ -488,10 +489,32 @@ proceedUntilFixedPoint state = do
     then return state
     else proceedUntilFixedPoint newState
 
+-- Provide feedback for pull requests where 'needsFeedback' is set.
+feedback :: (PullRequestId, PullRequest) -> ProjectState -> Action ProjectState
+feedback (prId, pr) state = case Pr.classifyPullRequest pr of
```
Comment (ruuda) [inline src/Logic.hs:494]: I think we could split this into two parts:

* A pure function `describeStatus :: (PullRequestId, PullRequest) -> ProjectState -> Text`
* A function that walks all pull requests that need feeback, leaves a comment with the result of `describeStatus`, and then unsets the flag.

`describeStatus` should exhaustively describe every status that a pull request can be in, in particular the situation where a pull request is approved and integrated, but the build failed. That way, when you leave an approval comment on such a PR, Hoff would reply that it’s not going to take any further action on the pull request.

It might even be possible to convert all existing cases where we leave a comment into this feedback mechanism.

File: tests/Spec.hs [hunk 2]
```diff
@@ -696,7 +699,8 @@ main = hspec $ do
               Project.author              = "rachael",
               Project.approvedBy          = Just "deckard",
               Project.integrationStatus   = Project.NotIntegrated,
-              Project.integrationAttempts = []
+              Project.integrationAttempts = [],
+              Project.needsFeedback       = False
             }
           prMap = IntMap.fromList [(1, pullRequest1), (2, pullRequest2)]
           -- After a successful push, the state of pull request 1 will still be
```
Comment (ruuda) [inline tests/Spec.hs:706]: We should also add tests for the cases mentioned in https://github.com/channable/hoff/issues/53#issuecomment-659278435. It’s a good idea to add a failing test first, to make sure that we can reproduce the bug. Then after implementing the fix, the test should pass.

Comment (splintah) [reply tests/Spec.hs]: In fd95f6c I added a test that reproduces the bug (I think), could you look at that?

It fails with the following message:

```
  1) Logic.proceedUntilFixedPoint reports the build status if a user retries the same commit
       expected: [AIsReviewer (Username "deckard"),ALeaveComment (PullRequestId 1) "Pull request approved by @deckard, rebasing now.",ATryIntegrate "Merge #1\n\nApproved-by: deckard" (refs/pull/1/head,a39),ALeaveComment (PullRequestId 1) "Rebased as b71, waiting for CI \8230",ALeaveComment (PullRequestId 1) "The build failed.",AIsReviewer (Username "deckard"),ALeaveComment (PullRequestId 1) "The build failed."]
        but got: [AIsReviewer (Username "deckard"),ALeaveComment (PullRequestId 1) "Pull request approved by @deckard, rebasing now.",ATryIntegrate "Merge #1\n\nApproved-by: deckard" (refs/pull/1/head,a39),ALeaveComment (PullRequestId 1) "Rebased as b71, waiting for CI \8230",ALeaveComment (PullRequestId 1) "The build failed.",AIsReviewer (Username "deckard"),ALeaveComment (PullRequestId 1) "Pull request approved by @deckard, rebasing now."]
```

Comment (ruuda) [reply tests/Spec.hs]: Yes, that test looks good!

**Comment by splintah** [comment]
The changes in b4cdc78 actually don't fix the test that reproduces the bug of #53:

```
9) Logic.proceedUntilFixedPoint reports the build status if a user retries the same commit
expected:
[ AIsReviewer (Username "deckard")
, ALeaveComment (PullRequestId 1) "Pull request approved by @deckard, rebasing now."
, ATryIntegrate "Merge #1\n\nApproved-by: deckard" (refs/pull/1/head,a39)
, ALeaveComment (PullRequestId 1) "Rebased as b71, waiting for CI \8230"
, ALeaveComment (PullRequestId 1) "The build failed."
, AIsReviewer (Username "deckard"),
, ALeaveComment (PullRequestId 1) "The build failed."
]
but got:
[ AIsReviewer (Username "deckard")
, ATryIntegrate "Merge #1\n\nApproved-by: deckard" (refs/pull/1/head,a39)
, ALeaveComment (PullRequestId 1) "Rebased as b71, waiting for CI \8230"
, ALeaveComment (PullRequestId 1) "The build failed."
, AIsReviewer (Username "deckard")
, ALeaveComment (PullRequestId 1) "The build failed."
]
```

The comment ‘pull request approved’ is not emitted, because the comments will only be sent after `processUnitFixedPoint` is finished.

We might want to do the comment handling in `proceedUntilFixedPoint`, then. @ruuda, what do you think of this?

**Comment by splintah** [comment]
> We might want to do the comment handling in `proceedUntilFixedPoint`, then.

This actually seems to work! The test that replicates the bug is passing and all old behaviour is preserved (according to the tests, that is).

**Comment by ruuda** [comment]
Yeah that makes sense to do, so it comments on the intermediate steps as well.

File: src/Logic.hs [hunk 3]
```diff
@@ -483,11 +477,65 @@ pushCandidate (pullRequestId, pullRequest) state = do
 -- effects if it does not change the state.
 proceedUntilFixedPoint :: ProjectState -> Action ProjectState
 proceedUntilFixedPoint state = do
-  newState <- proceed state
+  newState <- provideFeedback state >>= proceed
```
Comment (ruuda) [inline src/Logic.hs:480]: Ooh actually, after writing it this way, it is obvious what we should do! `provideFeedback` should just be part of `proceed`! It is only a cosmetic change, the behavior is the same, but it suddenly falls into place :smile: 

The purpose of `proceed` is to find the next thing it can make progress on, and to perform that action. So the first thing `proceed` should do is to check if any PRs need feedback, and if so, provide it, and unset the flag. Then once all feedback has been provided, `proceed` can no longer make progress there, so then it will continue with whatever it currently already does.

File: src/Logic.hs [hunk 4]
```diff
@@ -483,11 +477,65 @@ pushCandidate (pullRequestId, pullRequest) state = do
...
+    getIntegrationSha :: PullRequest -> Maybe Sha
+    getIntegrationSha pullRequest =
+      case Pr.integrationStatus pullRequest of
+        Integrated sha _ -> Just sha
+        _                -> Nothing
+
+    getIntegrationTargetBranch :: PullRequest -> Maybe Branch
+    getIntegrationTargetBranch pullRequest =
+      case Pr.integrationStatus pullRequest of
+        Conflicted targetBranch -> Just targetBranch
```
Comment (ruuda) [inline src/Logic.hs:521]: If it doesn't break other usages of `PullRequestStatus`, we might put the conflicted branch (and also the integrated sha above) in `PrStatusFailedConflict`. I think that would eliminate a few of these impossible branches and `fromJust`.

File: src/Logic.hs [hunk 5]
```diff
@@ -483,11 +477,65 @@ pushCandidate (pullRequestId, pullRequest) state = do
...
+        _                       -> Nothing
+
+-- Leave a comment with the feedback from 'describeStatus' and set the
+-- 'needsFeedback' flag to 'False'.
+feedback :: (PullRequestId, PullRequest) -> ProjectState -> Action ProjectState
```
Comment (ruuda) [inline src/Logic.hs:526]: A better name then would be something like `leaveFeedback`, as this also posts the comment.

File: src/Logic.hs (hunk 4 above)
Comment (splintah) [reply src/Logic.hs:521]: > If it doesn't break other usages

Well, it does, but it wouldn't be too hard to fix.

Comment (ruuda) [reply src/Logic.hs:523]: Yeah we need to add the `_` in matches of course, but do we do something like putting them in a `HashMap`? (I don’t recall from the top of my head how the grouping in the webinterface is implemented).

Comment (ruuda) [reply src/Logic.hs:523]: I’ll leave it up to you then. We do eventually want to merge the integration and approval status, and at that point `PullRequestStatus` would become obsolete, and we will eliminate many more of these matches that should be unreachable. So we could also leave it like this for now, and fix it as part of the bigger refactor.

Comment (splintah) [reply src/Logic.hs:523]: > but do we do something like putting them in a `HashMap`?

```sh
$ rg HashMap src
```

(No output.)

I guess not :smile:.

Comment (splintah) [reply src/Logic.hs:523]: > So we could also leave it like this for now, and fix it as part of the bigger refactor.

Yeah, I think that's better.

Comment (ruuda) [reply src/Logic.hs:523]: Ah this was the part I was worried about: https://github.com/channable/hoff/blob/b21da7705f90f8c87f9b05e3e5ba65deb41f459d/src/WebInterface.hs#L149-L177

We do use `==` but we can add a helper for matching.

**Comment by splintah** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved by @splintah, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as c5af6cef14a3cb4e3acad29754166270d2435238, waiting for CI …
